Fixed bugs in sm-*db* utils and updated copyright

diff --git a/sm-create-db b/sm-create-db
--- a/sm-create-db
+++ b/sm-create-db
@@ -1,7 +1,7 @@
 #!/usr/bin/bash
 #
-# Create a MySQL/PostgreSQL database for a SmartMachine.
-# Copyright (c) 2014 Joyent Inc., All rights reserved.
+# Create a MySQL/PostgreSQL database for a SmartOS VM.
+# Copyright (c) 2015 Joyent Inc., All rights reserved.
 
 set -o errexit
 set -o pipefail
@@ -50,40 +50,38 @@ else
 fi
 
 export LANG=C
-PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
+PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
 
 create_mysqldb() {
-	hash mysql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - mysql was not found in your PATH." && exit 2;
+	hash mysql 2>/dev/null || { echo "* ERROR - mysql was not found in your PATH." && exit 2; }
 
-	[[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to list the databases." && exit 2;
+	[[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to create a database." && exit 2;
 
-        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1
-        [[ $? -eq 1 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
         [[ $(mysql -u${DB_USER} -p${DB_PASS} -e "use ${DB_NAME};" &>/dev/null)$? -eq 1 ]] || \
                 { echo "* ERROR - Database ${DB_NAME} already exists." && exit 2; }
 
-	mysql -u${DB_USER} -p${DB_PASS} -e "create database ${DB_NAME};" > /dev/null 2>&1
-	[[ $? -eq 1 ]] && echo "* ERROR - There was an error creating your database." && exit 2;
+	mysql -u${DB_USER} -p${DB_PASS} -e "create database ${DB_NAME};" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error creating your database." && exit 2; }
 
 	echo "* Created MySQL database ${DB_NAME}.";
 }
 create_postgresdb() {
-	hash psql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - psql was not found in your PATH." && exit 2;
+	hash psql 2>/dev/null || { echo "* ERROR - psql was not found in your PATH." && exit 2; }
 
 	export PGPASSWORD=${DB_PASS};
 
-        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to list the databases." && exit 2;
+        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to create a database." && exit 2;
 
-        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1
-        [[ $? > 0 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1 || \
+ 		{ echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
 	[[ $(psql -U ${DB_USER} --list | egrep "\b${DB_NAME}\b") ]] && echo "* ERROR - Database ${DB_NAME} already exists." && exit 2;
 
-	psql -U ${DB_USER} -c "create database ${DB_NAME};" > /dev/null 2>&1
-	[[ $? > 0 ]] && echo "* ERROR - There was an error creating your database." && exit 2;
+	psql -U ${DB_USER} -c "create database ${DB_NAME};" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error creating your database." && exit 2; }
 
 	echo "* Created PostgreSQL database ${DB_NAME}.";
 }
diff --git a/sm-create-dbuser b/sm-create-dbuser
--- a/sm-create-dbuser
+++ b/sm-create-dbuser
@@ -1,7 +1,12 @@
 #!/usr/bin/bash
 #
-# Create a MySQL/PostgreSQL database user for a SmartMachine.
-# Copyright (c) 2014 Joyent Inc., All rights reserved.
+# Create a MySQL/PostgreSQL database user for a SmartOS VM.
+# Copyright (c) 2015 Joyent Inc., All rights reserved.
+
+set -o errexit
+set -o pipefail
+#set -o nounset
+#set -o xtrace
 
 usage() {
 cat << EOF
@@ -50,45 +55,43 @@ else
 fi
 
 export LANG=C
-PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
+PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
 [[ ${DB_NAME} = "all" ]] && DB_NAME='*';
 [[ ${DB_TYPE} = "postgresql" ]] && [[ ${DB_NAME} = "*" ]] && echo "* ERROR - 'all' can only be used with MySQL." && exit 2; 
 
 create_mysqldbuser() {
-	hash mysql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - mysql was not found in your PATH." && exit 2;
+	hash mysql 2>/dev/null || { echo "* ERROR - mysql was not found in your PATH." && exit 2; }
 
-        [[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to list the databases." && exit 2;
+        [[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to create a user." && exit 2;
 
-        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1
-        [[ $? -eq 1 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
-	mysql -u${DB_USER} -p${DB_PASS} -e "grant all on ${DB_NAME}.* to '${DB_CREATEUSER}'@'%' identified by '${DB_CREATEPASS}'; flush privileges;" > /dev/null 2>&1
-	[[ $? -eq 1 ]] && echo "* ERROR - There was an error creating your user." && exit 2;
+	mysql -u${DB_USER} -p${DB_PASS} -e "grant all on ${DB_NAME}.* to '${DB_CREATEUSER}'@'%' identified by '${DB_CREATEPASS}'; flush privileges;" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error creating your user." && exit 2; }
 
-	mysql -u${DB_USER} -p${DB_PASS} -e "grant all on ${DB_NAME}.* to '${DB_CREATEUSER}'@'localhost' identified by '${DB_CREATEPASS}'; flush privileges;" > /dev/null 2>&1
-	[[ $? -eq 1 ]] && echo "* ERROR - There was an error creating your user." && exit 2;
+	mysql -u${DB_USER} -p${DB_PASS} -e "grant all on ${DB_NAME}.* to '${DB_CREATEUSER}'@'localhost' identified by '${DB_CREATEPASS}'; flush privileges;" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error creating your user." && exit 2; }
 
 	[[ ${DB_NAME} = "*" ]] && DB_NAME="all";
 
 	echo "* Created MySQL user ${DB_CREATEUSER} pass ${DB_CREATEPASS} with access to ${DB_NAME} from anywhere.";
 }
 create_postgresdbuser() {
-	hash psql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - psql was not found in your PATH." && exit 2;
+	hash psql 2>/dev/null || { echo "* ERROR - psql was not found in your PATH." && exit 2; }
 
 	export PGPASSWORD=${DB_PASS};
 
-        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to list the databases." && exit 2;
+        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to create a user." && exit 2;
 
-        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1
-        [[ $? > 0 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
 	[[ ! $(psql -U ${DB_USER} --list | egrep "\b${DB_NAME}\b") ]] && echo "* ERROR - Database ${DB_NAME} doesn't exist." && exit 2;
 	[[ $(psql -U ${DB_USER} -t -A -c "select usename from pg_user where usename = '${DB_CREATEUSER}'";) ]] && echo "* ERROR - Username ${DB_CREATEUSER} already exists." && exit 2;
 
-	psql -U ${DB_USER} -c "create role ${DB_CREATEUSER} with password '${DB_CREATEPASS}' nosuperuser nocreatedb nocreaterole inherit login; alter database ${DB_NAME} owner to ${DB_CREATEUSER};" > /dev/null 2>&1
-	[[ $? > 0 ]] && echo "* ERROR - There was an error creating your user." && exit 2;
+	psql -U ${DB_USER} -c "create role ${DB_CREATEUSER} with password '${DB_CREATEPASS}' nosuperuser nocreatedb nocreaterole inherit login; alter database ${DB_NAME} owner to ${DB_CREATEUSER};" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error creating your user." && exit 2; }
 
 	echo "* Created PostgreSQL user ${DB_CREATEUSER} pass ${DB_CREATEPASS} with access to ${DB_NAME}.";
 }
@@ -96,12 +99,12 @@ create_postgresdbuser() {
 case $DB_TYPE in
 	mysql)
 		DB_USER=${DB_USER:-root};
-		DB_PASS=${DB_PASS:-`mdata-get mysql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get mysql_pw 2> /dev/null)} || DB_PASS="null";
 		create_mysqldbuser;
 		;;
 	postgresql)
 		DB_USER=${DB_USER:-postgres};
-		DB_PASS=${DB_PASS:-`mdata-get pgsql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get pgsql_pw 2> /dev/null)} || DB_PASS="null";
 		create_postgresdbuser;
 		;;
 	*)
diff --git a/sm-list-dbs b/sm-list-dbs
--- a/sm-list-dbs
+++ b/sm-list-dbs
@@ -1,7 +1,12 @@
 #!/usr/bin/bash
 #
-# List MySQL/PostgreSQL databases for a SmartMachine.
-# Copyright (c) 2014 Joyent Inc., All rights reserved.
+# List MySQL/PostgreSQL databases for a SmartOS VM.
+# Copyright (c) 2015 Joyent Inc., All rights reserved.
+
+set -o errexit
+set -o pipefail
+#set -o nounset
+#set -o xtrace
 
 usage() {
 cat << EOF
@@ -43,49 +48,47 @@ else
 fi
 
 export LANG=C
-PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
+PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
 ZONENAME=$(zonename);
 
 list_mysqldb() {
-	hash mysql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - mysql was not found in your PATH." && exit 2;
+	hash mysql 2>/dev/null || { echo "* ERROR - mysql was not found in your PATH." && exit 2; }
 
 	[[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to list the databases." && exit 2;
 
-	mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1
-	[[ $? -eq 1 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
 	echo "* Listing MySQL databases for ${ZONENAME}..";
 
-	mysql -u${DB_USER} -p${DB_PASS} -Ns -e "show databases;" 2> /dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - There was an error listing the databases." && exit 2;
+	mysql -u${DB_USER} -p${DB_PASS} -Ns -e "show databases;" 2> /dev/null || \
+		{ echo "* ERROR - There was an error listing the databases." && exit 2; }
 }
 list_postgresdb() {
-	hash psql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - psql was not found in your PATH." && exit 2;
+	hash psql 2>/dev/null || { echo "* ERROR - psql was not found in your PATH." && exit 2; }
 
 	export PGPASSWORD=${DB_PASS};
 
 	[[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to list the databases." && exit 2;
 
-	psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1
-	[[ $? > 0 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
 	echo "* Listing PostgreSQL databases for ${ZONENAME}..";
 
-	psql -U ${DB_USER} -t -A -c 'select datname from pg_database;' 2> /dev/null
-	[[ $? > 0 ]] && echo "* ERROR - There was an error listing the databases." && exit 2;
+	psql -U ${DB_USER} -t -A -c 'select datname from pg_database;' 2> /dev/null || \
+		{ echo "* ERROR - There was an error listing the databases." && exit 2; }
 }
 
 case $DB_TYPE in
 	mysql)
 		DB_USER=${DB_USER:-root};
-		DB_PASS=${DB_PASS:-`mdata-get mysql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get mysql_pw 2> /dev/null)} || DB_PASS="null";
 		list_mysqldb;
 		;;
 	postgresql)
 		DB_USER=${DB_USER:-postgres};
-		DB_PASS=${DB_PASS:-`mdata-get pgsql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get pgsql_pw 2> /dev/null)} || DB_PASS="null";
 		list_postgresdb;
 		;;
 	*)
diff --git a/sm-remove-db b/sm-remove-db
--- a/sm-remove-db
+++ b/sm-remove-db
@@ -1,7 +1,12 @@
 #!/usr/bin/bash
 #
-# Remove a MySQL/PostgreSQL database for a SmartMachine.
-# Copyright (c) 2014 Joyent Inc., All rights reserved.
+# Remove a MySQL/PostgreSQL database for a SmartOS VM.
+# Copyright (c) 2015 Joyent Inc., All rights reserved.
+
+set -o errexit
+set -o pipefail
+#set -o nounset
+#set -o xtrace
 
 usage() {
 cat << EOF
@@ -45,40 +50,39 @@ else
 fi
 
 export LANG=C
-PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
+PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
 
 remove_mysqldb() {
-	hash mysql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - mysql was not found in your PATH." && exit 2;
 
-        [[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to list the databases." && exit 2;
+        hash mysql 2>/dev/null || { echo "* ERROR - mysql was not found in your PATH." && exit 2; }
 
-        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1
-        [[ $? -eq 1 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        [[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to remove a database." && exit 2;
 
-	mysql -u${DB_USER} -p${DB_PASS} -e "use ${DB_NAME};" > /dev/null 2>&1
-	[[ $? -eq 1 ]] && echo "* ERROR - Database ${DB_NAME} doesn't exist." && exit 2;
+        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
-	mysql -u${DB_USER} -p${DB_PASS} -e "drop database ${DB_NAME};" > /dev/null 2>&1
-	[[ $? -eq 1 ]] && echo "* ERROR - There was an error removing your database." && exit 2;
+	mysql -u${DB_USER} -p${DB_PASS} -e "use ${DB_NAME};" > /dev/null 2>&1 || \
+		{ echo "* ERROR - Database ${DB_NAME} doesn't exist." && exit 2; }
+
+	mysql -u${DB_USER} -p${DB_PASS} -e "drop database ${DB_NAME};" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error removing your database." && exit 2; }
 
 	echo "* Removed MySQL database ${DB_NAME}.";
 }
 remove_postgresdb() {
-	hash psql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - psql was not found in your PATH." && exit 2;
+        hash psql 2>/dev/null || { echo "* ERROR - psql was not found in your PATH." && exit 2; }
 
-	export PGPASSWORD=${DB_PASS};
+        export PGPASSWORD=${DB_PASS};
 
-        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to list the databases." && exit 2;
+        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to remove a database." && exit 2;
 
-        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1
-        [[ $? > 0 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
 	[[ ! $(psql -U ${DB_USER} --list | egrep "\b${DB_NAME}\b") ]] && echo "* ERROR - Database ${DB_NAME} doesn't exist." && exit 2;
 
-	psql -U ${DB_USER} -c "drop database ${DB_NAME};" > /dev/null 2>&1
-	[[ $? > 0 ]] && echo "* ERROR - There was an error removing your database." && exit 2;
+	psql -U ${DB_USER} -c "drop database ${DB_NAME};" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error removing your database." && exit 2; }
 
 	echo "* Removed PostgreSQL database ${DB_NAME}.";
 }
@@ -86,12 +90,12 @@ remove_postgresdb() {
 case $DB_TYPE in
 	mysql)
 		DB_USER=${DB_USER:-root};
-		DB_PASS=${DB_PASS:-`mdata-get mysql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get mysql_pw 2> /dev/null)} || DB_PASS="null";
 		remove_mysqldb;
 		;;
 	postgresql)
 		DB_USER=${DB_USER:-postgres};
-		DB_PASS=${DB_PASS:-`mdata-get pgsql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get pgsql_pw 2> /dev/null)} || DB_PASS="null";
 		remove_postgresdb;
 		;;
 	*)
diff --git a/sm-remove-dbuser b/sm-remove-dbuser
--- a/sm-remove-dbuser
+++ b/sm-remove-dbuser
@@ -1,7 +1,12 @@
 #!/usr/bin/bash
 #
-# Remove a MySQL/PostgreSQL database for a SmartMachine.
-# Copyright (c) 2014 Joyent Inc., All rights reserved.
+# Remove a MySQL/PostgreSQL database for a SmartOS VM.
+# Copyright (c) 2015 Joyent Inc., All rights reserved.
+
+set -o errexit
+set -o pipefail
+#set -o nounset
+#set -o xtrace
 
 usage() {
 cat << EOF
@@ -45,40 +50,38 @@ else
 fi
 
 export LANG=C
-PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
+PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
 
 remove_mysqldbuser() {
-	hash mysql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - mysql was not found in your PATH." && exit 2;
+        hash mysql 2>/dev/null || { echo "* ERROR - mysql was not found in your PATH." && exit 2; }
 
-        [[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to list the databases." && exit 2;
+        [[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to remove a user." && exit 2;
 
-        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1
-        [[ $? -eq 1 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
-	mysql -u${DB_USER} -p${DB_PASS} -e "delete from mysql.user where User='${DB_REMOVEUSER}';" > /dev/null 2>&1
-	[[ $? -eq 1 ]] && echo "* ERROR - There was an error removing the user." && exit 2;
+	mysql -u${DB_USER} -p${DB_PASS} -e "delete from mysql.user where User='${DB_REMOVEUSER}';" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error removing the user." && exit 2; }
 
 	echo "* Removed MySQL user ${DB_REMOVEUSER}.";
 }
 remove_postgresdbuser() {
-	hash psql &>/dev/null
-	[[ $? -eq 1 ]] && echo "* ERROR - psql was not found in your PATH." && exit 2;
+        hash psql 2>/dev/null || { echo "* ERROR - psql was not found in your PATH." && exit 2; }
 
-	export PGPASSWORD=${DB_PASS};
+        export PGPASSWORD=${DB_PASS};
 
-        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to list the databases." && exit 2;
+        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to remove a user." && exit 2;
 
-        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1
-        [[ $? > 0 ]] && echo "* ERROR - Can't connect with username password specified." && exit 2;
+        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1 || \
+                { echo "* ERROR - Can't connect with username password specified." && exit 2; }
 
 	[[ ! $(psql -U ${DB_USER} -t -A -c "select usename from pg_user where usename = '${DB_REMOVEUSER}'";) ]] && echo "* ERROR - Username ${DB_REMOVEUSER} doesn't exist." && exit 2;
 
 	DB_POSTGRES_ID=$(psql -U ${DB_USER} -t -A -c "select usesysid from pg_shadow where usename='postgres'";);
 	DB_REMOVEUSER_ID=$(psql -U ${DB_USER} -t -A -c "select usesysid from pg_shadow where usename='${DB_REMOVEUSER}'";);
 
-	psql -U ${DB_USER} -c "update pg_database set datdba='${DB_POSTGRES_ID}' where datdba='${DB_REMOVEUSER_ID}';" > /dev/null 2>&1;
-	[[ $? > 0 ]] && echo "* ERROR - There was an error removing the user." && exit 2;
+	psql -U ${DB_USER} -c "update pg_database set datdba='${DB_POSTGRES_ID}' where datdba='${DB_REMOVEUSER_ID}';" > /dev/null 2>&1 || \
+		{ echo "* ERROR - There was an error removing the user." && exit 2; }
 	psql -U ${DB_USER} -c "drop user ${DB_REMOVEUSER};"
 
 #	psql -U ${DB_USER} -c "revoke all on database dbname from username; drop user ${DB_REMOVEUSER};" > /dev/null 2>&1
@@ -90,12 +93,12 @@ remove_postgresdbuser() {
 case $DB_TYPE in
 	mysql)
 		DB_USER=${DB_USER:-root};
-		DB_PASS=${DB_PASS:-`mdata-get mysql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get mysql_pw 2> /dev/null)} || DB_PASS="null";
 		remove_mysqldbuser;
 		;;
 	postgresql)
 		DB_USER=${DB_USER:-postgres};
-		DB_PASS=${DB_PASS:-`mdata-get pgsql_pw 2> /dev/null`} || DB_PASS="null";
+		DB_PASS=${DB_PASS:-$(mdata-get pgsql_pw 2> /dev/null)} || DB_PASS="null";
 		remove_postgresdbuser;
 		;;
 	*)
