Significant rewrite of parts of zoneinit, fixes at least DATASET-582, DATASET-584, DATASET-585, DATASET-577.
The workflow changes so that:

- If full metadata available (on SDC7), it is used instead of zoneconfig
  (otherwise a fallback to zoneconfig is attempted). All the logic happens
  in includes/02-config.sh now (deprecates 00-init.sh, 03-dupipcheck.sh
  and 03-ips.sh).
- Provisioning starts when /var/svc/provisioning exists. In case zoneconfig
  is found, /var/svc/provisioning is created as an easy measure to stay
  compatible with 6.5 platforms.
- Whenever an error occurs during the zoneinit run, /var/svc/provisioning
  is renamed to /var/svc/provision_failure, which vmadm's watch process
  should recognize and mark the machine as failed.
- If no error occured, zoneinit shuts itself down normally. On next reboot,
  mdata:execute gets invoked. It will optionally execute the user-script
  (if any), and renamed /var/svc/provisioning to /var/svc/provision-success
  (which, again, should be recognized by the provisioner as a success flag).
- The user-script can optionally touch /var/svc/provision_ongoing, which
  bypasses the above success logic, and it is understood the user will
  implement something different to change /var/svc/provisioning into
  /var/svc/provision_success.
- The mdata script & SMF support is integrated into the smtools package now
  (and set up by sm-prepare-image), because it's tightly coupled with the
  provisioning process now, so really part of the zoneinit.
- Since mdata:execute is now used to conclude provisioning, it is enabled
  by default. It just won't invoke the user-script if none is found.
- A /var/zoneinit/zoneinit.json file will be left behind by sm-prepare-image,
  which contains zoneinit version (starting with 1.5.0) and any feature flags,
  e.g. '"reboot": true' (to signify that the image will reboot once at the end
  of the provision), and '"zoneconfig": false' (that this image doesn't place
  a hard requirement on zoneconfig file being present).

diff --git a/zoneinit/zoneinit b/zoneinit/zoneinit
--- a/zoneinit/zoneinit
+++ b/zoneinit/zoneinit
@@ -9,28 +9,42 @@ set -o xtrace
 BASE=$(dirname $0)
 ZONECONFIG=/root/zoneconfig
 
-# Pretend success when not under SMF, not starting, or a dev zone
-if [ "${SMF_METHOD}" != "start" ] || [ ! -e ${ZONECONFIG} ]; then
-  exit 0
-fi
+# This script should only continue if
+#
+#  1) executed as a SMF start method; and
+#  2) /var/svc/provisioning exist.
+#
+# Otherwise, pretend success but do nothing
+#
+# Pre-create /var/svc/provisioning if /root/zoneconfig exists
+# to stay backwards compatible.
+
+[ -e ${ZONECONFIG} ] && touch /var/svc/provisioning
+[ "${SMF_METHOD}" == "start" ] && [ -e /var/svc/provisioning ] || exit 0
 
 function log {
   local WHERE=$(basename ${INC-zoneinit})
   echo "${WHERE}: $1"
 }
 
-function error {
+function exit_handler {
   local WHERE=$(basename ${INC-zoneinit})
-  local ERROR=$2
-  [ $((${ERROR}+0)) -eq 0 ] && unset ERROR
-  echo "${WHERE}: ERROR $1"
+  local EXITCODE=${2:-95}
 
-  # Status 95 tells the SMF restarter to not try again, and fail fatally.
-  # We do not have atomic rollback capability here, so we shouldn't ever
-  # attempt to resume a failed zoneinit. Instead - succeed or fail in
-  # one attempt only.
-  exit ${ERROR:-95}
+  if [ ${EXITCODE} -gt 0 ]; then
+    echo "${WHERE}: $1 ${EXITCODE}"
+
+    # Renaming 'provisioning' to 'provision_failure' tells the provisioner
+    # that we failed and the machine is no good
+
+    [ -e /var/svc/provisioning ] && mv /var/svc/provision{ing,_failure}
+
+    # Status 95 tells the SMF restarter to fail fatally (not try again)
+    exit 95
+  fi
 }
+
+trap 'exit_handler "received exit status" $?' EXIT
 
 START_TIME=$(date +%s)
 log "(start)"
@@ -40,7 +54,6 @@ for INC in ${BASE}/includes/*.sh
 do
   log "(start)"
   source ${INC}
-  log "(finish)"
 done
 unset INC
 
